services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: 'kpd-frontend'
    depends_on:
      - backend
    ports:
      - '8080:80'
    networks:
      - frontend
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: 'kpd-backend'
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - '4000:3001'
    env_file:
      - .env
  postgres:
    restart: always
    container_name: postgres
    image: 'postgres'
    volumes:
      - postgres_data:/data/postgres/
    env_file:
      - .env
    networks:
      - backend
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend

volumes:
  postgres_data:

networks:
  frontend:
  backend:
